// Generated by gencpp from file mavros_msgs/ActuatorMotors.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_ACTUATORMOTORS_H
#define MAVROS_MSGS_MESSAGE_ACTUATORMOTORS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mavros_msgs
{
template <class ContainerAllocator>
struct ActuatorMotors_
{
  typedef ActuatorMotors_<ContainerAllocator> Type;

  ActuatorMotors_()
    : header()
    , control()  {
      control.assign(0.0);
  }
  ActuatorMotors_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , control()  {
  (void)_alloc;
      control.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<float, 12>  _control_type;
  _control_type control;





  typedef boost::shared_ptr< ::mavros_msgs::ActuatorMotors_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavros_msgs::ActuatorMotors_<ContainerAllocator> const> ConstPtr;

}; // struct ActuatorMotors_

typedef ::mavros_msgs::ActuatorMotors_<std::allocator<void> > ActuatorMotors;

typedef boost::shared_ptr< ::mavros_msgs::ActuatorMotors > ActuatorMotorsPtr;
typedef boost::shared_ptr< ::mavros_msgs::ActuatorMotors const> ActuatorMotorsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavros_msgs::ActuatorMotors_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavros_msgs::ActuatorMotors_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mavros_msgs::ActuatorMotors_<ContainerAllocator1> & lhs, const ::mavros_msgs::ActuatorMotors_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.control == rhs.control;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mavros_msgs::ActuatorMotors_<ContainerAllocator1> & lhs, const ::mavros_msgs::ActuatorMotors_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mavros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::ActuatorMotors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::ActuatorMotors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::ActuatorMotors_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::ActuatorMotors_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::ActuatorMotors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::ActuatorMotors_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavros_msgs::ActuatorMotors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f943f6306cbf000b000ac2cf4ec99395";
  }

  static const char* value(const ::mavros_msgs::ActuatorMotors_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf943f6306cbf000bULL;
  static const uint64_t static_value2 = 0x000ac2cf4ec99395ULL;
};

template<class ContainerAllocator>
struct DataType< ::mavros_msgs::ActuatorMotors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavros_msgs/ActuatorMotors";
  }

  static const char* value(const ::mavros_msgs::ActuatorMotors_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavros_msgs::ActuatorMotors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"std_msgs/Header header\n"
"\n"
"float32[12] control # range: [-1, 1], where 1 means maximum positive thrust,\n"
"                    # -1 maximum negative (if not supported by the output, <0 maps to NaN),\n"
"                    # and NaN maps to disarmed (stop the motors)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mavros_msgs::ActuatorMotors_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavros_msgs::ActuatorMotors_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.control);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActuatorMotors_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavros_msgs::ActuatorMotors_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavros_msgs::ActuatorMotors_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "control[]" << std::endl;
    for (size_t i = 0; i < v.control.size(); ++i)
    {
      s << indent << "  control[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.control[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVROS_MSGS_MESSAGE_ACTUATORMOTORS_H
