// Generated by gencpp from file mavros_msgs/VehicleAttitude.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_VEHICLEATTITUDE_H
#define MAVROS_MSGS_MESSAGE_VEHICLEATTITUDE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mavros_msgs
{
template <class ContainerAllocator>
struct VehicleAttitude_
{
  typedef VehicleAttitude_<ContainerAllocator> Type;

  VehicleAttitude_()
    : header()
    , q_w(0.0)
    , q_x(0.0)
    , q_y(0.0)
    , q_z(0.0)
    , delta_q_w(0.0)
    , delta_q_x(0.0)
    , delta_q_y(0.0)
    , delta_q_z(0.0)  {
    }
  VehicleAttitude_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , q_w(0.0)
    , q_x(0.0)
    , q_y(0.0)
    , q_z(0.0)
    , delta_q_w(0.0)
    , delta_q_x(0.0)
    , delta_q_y(0.0)
    , delta_q_z(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _q_w_type;
  _q_w_type q_w;

   typedef float _q_x_type;
  _q_x_type q_x;

   typedef float _q_y_type;
  _q_y_type q_y;

   typedef float _q_z_type;
  _q_z_type q_z;

   typedef float _delta_q_w_type;
  _delta_q_w_type delta_q_w;

   typedef float _delta_q_x_type;
  _delta_q_x_type delta_q_x;

   typedef float _delta_q_y_type;
  _delta_q_y_type delta_q_y;

   typedef float _delta_q_z_type;
  _delta_q_z_type delta_q_z;





  typedef boost::shared_ptr< ::mavros_msgs::VehicleAttitude_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavros_msgs::VehicleAttitude_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleAttitude_

typedef ::mavros_msgs::VehicleAttitude_<std::allocator<void> > VehicleAttitude;

typedef boost::shared_ptr< ::mavros_msgs::VehicleAttitude > VehicleAttitudePtr;
typedef boost::shared_ptr< ::mavros_msgs::VehicleAttitude const> VehicleAttitudeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavros_msgs::VehicleAttitude_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavros_msgs::VehicleAttitude_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mavros_msgs::VehicleAttitude_<ContainerAllocator1> & lhs, const ::mavros_msgs::VehicleAttitude_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.q_w == rhs.q_w &&
    lhs.q_x == rhs.q_x &&
    lhs.q_y == rhs.q_y &&
    lhs.q_z == rhs.q_z &&
    lhs.delta_q_w == rhs.delta_q_w &&
    lhs.delta_q_x == rhs.delta_q_x &&
    lhs.delta_q_y == rhs.delta_q_y &&
    lhs.delta_q_z == rhs.delta_q_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mavros_msgs::VehicleAttitude_<ContainerAllocator1> & lhs, const ::mavros_msgs::VehicleAttitude_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mavros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::VehicleAttitude_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::VehicleAttitude_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::VehicleAttitude_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::VehicleAttitude_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::VehicleAttitude_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::VehicleAttitude_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavros_msgs::VehicleAttitude_<ContainerAllocator> >
{
  static const char* value()
  {
    return "87516def103d6cf916a4ef36cfc5dbdc";
  }

  static const char* value(const ::mavros_msgs::VehicleAttitude_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x87516def103d6cf9ULL;
  static const uint64_t static_value2 = 0x16a4ef36cfc5dbdcULL;
};

template<class ContainerAllocator>
struct DataType< ::mavros_msgs::VehicleAttitude_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavros_msgs/VehicleAttitude";
  }

  static const char* value(const ::mavros_msgs::VehicleAttitude_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavros_msgs::VehicleAttitude_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Represent Vehicle Attitude.\n"
"#\n"
"# VEHICLE_ATTITUDE message\n"
"\n"
"std_msgs/Header header\n"
"float32 q_w\n"
"float32 q_x\n"
"float32 q_y\n"
"float32 q_z\n"
"\n"
"float32 delta_q_w\n"
"float32 delta_q_x\n"
"float32 delta_q_y\n"
"float32 delta_q_z\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mavros_msgs::VehicleAttitude_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavros_msgs::VehicleAttitude_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.q_w);
      stream.next(m.q_x);
      stream.next(m.q_y);
      stream.next(m.q_z);
      stream.next(m.delta_q_w);
      stream.next(m.delta_q_x);
      stream.next(m.delta_q_y);
      stream.next(m.delta_q_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleAttitude_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavros_msgs::VehicleAttitude_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavros_msgs::VehicleAttitude_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "q_w: ";
    Printer<float>::stream(s, indent + "  ", v.q_w);
    s << indent << "q_x: ";
    Printer<float>::stream(s, indent + "  ", v.q_x);
    s << indent << "q_y: ";
    Printer<float>::stream(s, indent + "  ", v.q_y);
    s << indent << "q_z: ";
    Printer<float>::stream(s, indent + "  ", v.q_z);
    s << indent << "delta_q_w: ";
    Printer<float>::stream(s, indent + "  ", v.delta_q_w);
    s << indent << "delta_q_x: ";
    Printer<float>::stream(s, indent + "  ", v.delta_q_x);
    s << indent << "delta_q_y: ";
    Printer<float>::stream(s, indent + "  ", v.delta_q_y);
    s << indent << "delta_q_z: ";
    Printer<float>::stream(s, indent + "  ", v.delta_q_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVROS_MSGS_MESSAGE_VEHICLEATTITUDE_H
