// Generated by gencpp from file mavros_msgs/VehicleAngularVelocity.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_VEHICLEANGULARVELOCITY_H
#define MAVROS_MSGS_MESSAGE_VEHICLEANGULARVELOCITY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mavros_msgs
{
template <class ContainerAllocator>
struct VehicleAngularVelocity_
{
  typedef VehicleAngularVelocity_<ContainerAllocator> Type;

  VehicleAngularVelocity_()
    : header()
    , angular_velocity_x(0.0)
    , angular_velocity_y(0.0)
    , angular_velocity_z(0.0)  {
    }
  VehicleAngularVelocity_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , angular_velocity_x(0.0)
    , angular_velocity_y(0.0)
    , angular_velocity_z(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _angular_velocity_x_type;
  _angular_velocity_x_type angular_velocity_x;

   typedef float _angular_velocity_y_type;
  _angular_velocity_y_type angular_velocity_y;

   typedef float _angular_velocity_z_type;
  _angular_velocity_z_type angular_velocity_z;





  typedef boost::shared_ptr< ::mavros_msgs::VehicleAngularVelocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavros_msgs::VehicleAngularVelocity_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleAngularVelocity_

typedef ::mavros_msgs::VehicleAngularVelocity_<std::allocator<void> > VehicleAngularVelocity;

typedef boost::shared_ptr< ::mavros_msgs::VehicleAngularVelocity > VehicleAngularVelocityPtr;
typedef boost::shared_ptr< ::mavros_msgs::VehicleAngularVelocity const> VehicleAngularVelocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavros_msgs::VehicleAngularVelocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavros_msgs::VehicleAngularVelocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mavros_msgs::VehicleAngularVelocity_<ContainerAllocator1> & lhs, const ::mavros_msgs::VehicleAngularVelocity_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.angular_velocity_x == rhs.angular_velocity_x &&
    lhs.angular_velocity_y == rhs.angular_velocity_y &&
    lhs.angular_velocity_z == rhs.angular_velocity_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mavros_msgs::VehicleAngularVelocity_<ContainerAllocator1> & lhs, const ::mavros_msgs::VehicleAngularVelocity_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mavros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::VehicleAngularVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::VehicleAngularVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::VehicleAngularVelocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::VehicleAngularVelocity_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::VehicleAngularVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::VehicleAngularVelocity_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavros_msgs::VehicleAngularVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "80bcff4028995521ef7ef0004f2a63eb";
  }

  static const char* value(const ::mavros_msgs::VehicleAngularVelocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x80bcff4028995521ULL;
  static const uint64_t static_value2 = 0xef7ef0004f2a63ebULL;
};

template<class ContainerAllocator>
struct DataType< ::mavros_msgs::VehicleAngularVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavros_msgs/VehicleAngularVelocity";
  }

  static const char* value(const ::mavros_msgs::VehicleAngularVelocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavros_msgs::VehicleAngularVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Represent Vehicle Angular Velocity.\n"
"#\n"
"# VEHICLE_ANGULAR_VELOCITY message\n"
"\n"
"std_msgs/Header header\n"
"float32 angular_velocity_x\n"
"float32 angular_velocity_y\n"
"float32 angular_velocity_z\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mavros_msgs::VehicleAngularVelocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavros_msgs::VehicleAngularVelocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.angular_velocity_x);
      stream.next(m.angular_velocity_y);
      stream.next(m.angular_velocity_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleAngularVelocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavros_msgs::VehicleAngularVelocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavros_msgs::VehicleAngularVelocity_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "angular_velocity_x: ";
    Printer<float>::stream(s, indent + "  ", v.angular_velocity_x);
    s << indent << "angular_velocity_y: ";
    Printer<float>::stream(s, indent + "  ", v.angular_velocity_y);
    s << indent << "angular_velocity_z: ";
    Printer<float>::stream(s, indent + "  ", v.angular_velocity_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVROS_MSGS_MESSAGE_VEHICLEANGULARVELOCITY_H
