name: Build and Deploy

on:
  # workflow_dispatch: {}
  push:
    branches: [ "CD" ]

env:
  applicationfolder: src


jobs:
  build:
    name: Build and Package
    runs-on: Linux_x64_16core
    strategy:
      fail-fast: false
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            hashim/docker/cache
          key: ${{ runner.os }}-hashim
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-pf-aws-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # - name: Set up JDK 1.8
      #   uses: actions/setup-java@v1
      #   with:
      #     java-version: 1.8

      - name: chmod
        run: chmod -R +x ./.github

      - name: Get Actor ID
        id: get_actor_id
        run: |
             echo "::set-output name=actor_id::$(curl -s -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" https://api.github.com/users/${{ github.actor }} | jq -r .id)"

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3
      
      - name: Env
        run: |
          # ACTIONS_RUNTIME_TOKEN, ACTIONS_RUNTIME_URL should be exposed
          # env|sort
      - name: Build and push the tagged docker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{secrets.AWS_ECR_REPO}}
          IMAGE_TAG: latest
          triggering_actor: ${{ github.triggering_actor }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo ${{ github.triggering_actor }}
          docker buildx create --name hashimBuilder --driver=docker-container
          docker buildx build . --platform linux/arm64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG  \
          --builder=hashimBuilder \
          --push \
          --cache-to type=gha,mode=max,scope=$ECR_REGISTRY/$ECR_REPOSITORY:cache \
          --cache-from type=gha,scope=$ECR_REGISTRY/$ECR_REPOSITORY:cache \
          --progress=plain \
          --secret id=GITHUB_ID,env=triggering_actor \
          --secret id=GITHUB_TOKEN,env=PAT_TOKEN \
          --build-arg TARGET_ORIN="ON" \
          --build-arg TARGET="ORIN" \
          --build-arg opencv_url="geohashim/opencv:4.0.0" \
          --build-arg qt_url="geohashim/qt" \
          --build-arg USERNAME="hashim" \
          --build-arg WS_NAME="HEAR_FC" \
          --build-arg IS_PRODUCTION="TRUE" \
          --build-arg COMPILE_BRANCH="dev-sitl" 

      - name: Extract folder from Docker container
        env:
          ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{secrets.AWS_ECR_REPO}}
          IMAGE_TAG: latest
        run: |
          # Create a container from the image we just built (but don't run it)
          CONTAINER_ID=$(docker create $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG)

          # Create a directory to hold the extracted files
          mkdir -p extracted_files

          # Copy the folder from the container to the host
          # Replace /home/hashim/HEAR_FC/devel/lib with the actual path inside the container
          docker cp $CONTAINER_ID:/home/hashim/HEAR_FC/devel/lib ./extracted_files

          # Remove the container
          docker rm $CONTAINER_ID

      - name: Upload folder as artifact
        uses: actions/upload-artifact@v3
        with:
          name: extracted-container-files
          path: extracted_files



      # - name: Build and Package Maven
      #   id: package
      #   working-directory: ${{ env.applicationfolder }}
      #   run: $GITHUB_WORKSPACE/.github/scripts/build.sh

      # - name: Upload Artifact to s3
      #   working-directory: ${{ env.applicationfolder }}/target
      #   run: aws s3 cp *.war s3://${{ env.S3BUCKET }}/
        
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   environment: Dev
  #   permissions:
  #     id-token: write
  #     contents: read
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: aws-actions/configure-aws-credentials@v1
  #     with:
  #       role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
  #       role-session-name: GitHub-Action-Role
  #       aws-region: ${{ env.AWS_REGION }}
  #   - run: |
  #       echo "Deploying branch ${{ env.GITHUB_REF }} to ${{ github.event.inputs.environment }}"
  #       commit_hash=`git rev-parse HEAD`
  #       aws deploy create-deployment --application-name HearArchCodeDeploy --deployment-group-name HearArchCodeDeployGroupName --github-location repository=$GITHUB_REPOSITORY,commitId=$commit_hash --ignore-application-stop-failures
